import { ArrowRight, Check, FileSpreadsheet, MessageCircle, Ruler, ShieldCheck, UploadCloud } from "lucide-react";
import { Link } from "wouter";

const whatsappUrl = "https://wa.me/2250151610512?text=Bonjour%20Daouda%2C%20je%20souhaite%20en%20savoir%20plus%20sur%20M%C3%89TREXPERT%20IA%20PRO.";

const deliverables = [
  { title: "Métré structuré", description: "Postes, unités, quantités, facteurs et notes organisés pour faciliter la vérification." },
  { title: "DQE exploitable", description: "Une base de devis quantitatif estimatif dans un classeur Excel modifiable avec formules actives lorsque les données le permettent." },
  { title: "Contrôles et hypothèses", description: "Dimensions explicites, hypothèses, contrôles indépendants, limites et lots non traités clairement signalés." },
];

const steps = [
  { number: "01", title: "Transmettre", description: "Décrivez le projet et joignez un plan PDF ou une image si vous en disposez." },
  { number: "02", title: "Structurer", description: "L’assistance IA organise les informations, calcule les quantités et signale les ambiguïtés." },
  { number: "03", title: "Vérifier", description: "Relisez les hypothèses et contrôles avant d’utiliser le fichier dans votre étude." },
];

const audiences = ["Entrepreneurs et artisans BTP", "Architectes et bureaux d’études", "Promoteurs de petite ou moyenne taille", "Particuliers construisant leur maison"];

export default function Landing() {
  return (
    <main className="landing-page min-h-screen overflow-hidden bg-[#F4F0E8] text-[#17221D]">
      <div className="landing-grid pointer-events-none fixed inset-0 opacity-50" aria-hidden="true" />
      <header className="relative border-b border-[#CBD0C8] bg-[#F4F0E8]/95 backdrop-blur-sm">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-5 px-5 py-5 sm:px-8 lg:px-12">
          <Link href="/" className="flex items-center gap-3" aria-label="MÉTREXPERT IA PRO — accueil">
            <span className="flex h-10 w-10 items-center justify-center border border-[#B38945] bg-[#17221D] text-[#D0A85C]"><Ruler className="h-5 w-5" aria-hidden="true" /></span>
            <span><span className="block font-mono text-[9px] uppercase tracking-[0.3em] text-[#8A6B36]">Bureau d’études numérique</span><span className="block font-serif text-xl tracking-tight text-[#17221D]">MÉTREXPERT <span className="text-[#A8792F]">IA PRO</span></span></span>
          </Link>
          <nav className="hidden items-center gap-7 font-mono text-[10px] uppercase tracking-[0.16em] text-[#526159] md:flex" aria-label="Navigation principale"><a href="#livrables" className="transition-colors hover:text-[#A8792F]">Livrables</a><a href="#methode" className="transition-colors hover:text-[#A8792F]">Méthode</a><a href="#public" className="transition-colors hover:text-[#A8792F]">Pour qui</a><Link href="/etude" className="border border-[#17221D] px-4 py-2 text-[#17221D] transition-colors hover:bg-[#17221D] hover:text-[#F4F0E8]">Ouvrir l’étude</Link></nav>
          <Link href="/etude" className="border border-[#17221D] px-3 py-2 font-mono text-[10px] uppercase tracking-wider text-[#17221D] md:hidden">Commencer</Link>
        </div>
      </header>

      <section className="relative mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-16 sm:px-8 sm:pt-24 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:px-12 lg:pb-28">
        <div className="max-w-3xl"><p className="mb-6 font-mono text-[10px] uppercase tracking-[0.28em] text-[#A8792F]">Métré · Quantitatif · DQE · Côte d’Ivoire</p><h1 className="max-w-3xl font-serif text-[clamp(3.3rem,7vw,6.8rem)] leading-[0.91] tracking-[-0.055em] text-[#17221D]">Du plan brut<br />à une base de <em className="text-[#A8792F]">quantitatif.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#526159]">MÉTREXPERT IA PRO vous aide à transformer une description de chantier, des dimensions ou un plan en un métré structuré et un fichier Excel exploitable — avec hypothèses, contrôles et vérification humaine.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/etude" className="inline-flex h-12 items-center justify-center gap-3 bg-[#17221D] px-6 font-mono text-[10px] uppercase tracking-[0.16em] text-[#F4F0E8] transition-transform hover:-translate-y-0.5">Tester l’espace de génération <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link><a href={whatsappUrl} target="_blank" rel="noreferrer" className="inline-flex h-12 items-center justify-center gap-3 border border-[#A8792F] px-6 font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A6B36] transition-colors hover:bg-[#E9DFC9]"><MessageCircle className="h-4 w-4" aria-hidden="true" />Parler du projet</a></div><p className="mt-4 text-xs text-[#718078]">Un essai gratuit limité est disponible avec un téléphone ou un e-mail. Aucun message n’est envoyé automatiquement.</p></div>
        <div className="relative"><div className="absolute -inset-5 border border-[#D5B776]/50" aria-hidden="true" /><div className="relative border border-[#B9C0B8] bg-[#17221D] p-5 text-[#F4F0E8] shadow-[14px_14px_0_#DCCCA8] sm:p-7"><div className="flex items-start justify-between border-b border-[#4C5C52] pb-5"><div><p className="font-mono text-[9px] uppercase tracking-[0.26em] text-[#D0A85C]">Livrable type</p><h2 className="mt-2 font-serif text-3xl">Métré & DQE</h2></div><FileSpreadsheet className="h-7 w-7 text-[#D0A85C]" aria-hidden="true" /></div><div className="mt-6 grid grid-cols-[auto_1fr_auto] gap-x-4 gap-y-4 font-mono text-[10px] uppercase tracking-wider"><span className="text-[#D0A85C]">01</span><span className="text-[#AEB7B0]">Données d’entrée</span><span className="text-[#D0A85C]">OK</span><span className="text-[#D0A85C]">02</span><span className="text-[#AEB7B0]">Hypothèses & ouvertures</span><span className="text-[#D0A85C]">À LIRE</span><span className="text-[#D0A85C]">03</span><span className="text-[#AEB7B0]">Contrôles géométriques</span><span className="text-[#7C9A76]">PRÊT</span></div><div className="mt-7 border-t border-[#4C5C52] pt-5"><div className="flex items-end justify-between"><span className="font-mono text-[9px] uppercase tracking-wider text-[#AEB7B0]">Format de sortie</span><strong className="font-serif text-2xl text-[#D0A85C]">.XLSX</strong></div><p className="mt-3 text-sm leading-6 text-[#B8C1BA]">Modifiable, lisible et conçu pour être relu avant usage professionnel.</p></div></div></div>
      </section>

      <section id="livrables" className="relative border-y border-[#CBD0C8] bg-[#E8E4DA] py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="max-w-2xl"><p className="font-mono text-[10px] uppercase tracking-[0.28em] text-[#A8792F]">Ce que vous recevez</p><h2 className="mt-4 font-serif text-4xl leading-tight tracking-tight sm:text-5xl">Un livrable qui montre aussi ses limites.</h2><p className="mt-5 text-base leading-7 text-[#526159]">Le service ne remplace pas une validation technique. Il aide à organiser le travail et rend visibles les données manquantes, les hypothèses et les contrôles à relire.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{deliverables.map((item, index) => <article key={item.title} className="border border-[#B9C0B8] bg-[#F4F0E8] p-6"><span className="font-mono text-[10px] tracking-[0.2em] text-[#A8792F]">0{index + 1}</span><h3 className="mt-8 font-serif text-2xl text-[#17221D]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-[#5D6A62]">{item.description}</p></article>)}</div></div></section>

      <section id="methode" className="relative mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-24 lg:px-12"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.28em] text-[#A8792F]">Méthode de travail</p><h2 className="mt-4 font-serif text-4xl leading-tight tracking-tight sm:text-5xl">Trois étapes. Une relecture indispensable.</h2></div><div className="grid gap-0 border-t border-[#B9C0B8]">{steps.map((step) => <div key={step.number} className="grid gap-4 border-b border-[#B9C0B8] py-6 sm:grid-cols-[70px_170px_1fr] sm:items-start"><span className="font-mono text-sm text-[#A8792F]">{step.number}</span><h3 className="font-serif text-2xl text-[#17221D]">{step.title}</h3><p className="text-sm leading-6 text-[#5D6A62]">{step.description}</p></div>)}</div></div></section>

      <section id="public" className="relative bg-[#17221D] py-20 text-[#F4F0E8] sm:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[0.9fr_1.1fr] lg:px-12"><div><p className="font-mono text-[10px] uppercase tracking-[0.28em] text-[#D0A85C]">Pour vos projets en Côte d’Ivoire</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Pensé pour les études BTP du quotidien.</h2><p className="mt-5 max-w-xl text-base leading-7 text-[#B8C1BA]">À Yopougon, Abidjan et dans les grandes villes ivoiriennes, les informations de projet arrivent rarement dans un format parfaitement préparé. L’espace de génération est conçu pour partir de ce que vous avez déjà.</p></div><div className="grid gap-3 sm:grid-cols-2">{audiences.map((audience) => <div key={audience} className="flex items-start gap-3 border border-[#4C5C52] p-5"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#D0A85C]" aria-hidden="true" /><span className="text-sm leading-6 text-[#D9DDD7]">{audience}</span></div>)}<div className="border border-[#D0A85C] p-5 sm:col-span-2"><p className="font-mono text-[10px] uppercase tracking-wider text-[#D0A85C]">Important</p><p className="mt-2 text-sm leading-6 text-[#D9DDD7]">Les prix unitaires, lots inclus, lots exclus et hypothèses doivent être relus avant toute décision ou transmission client.</p></div></div></div></section>

      <section className="relative mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-24 lg:px-12"><div className="border border-[#B9C0B8] bg-[#E8E4DA] p-7 sm:p-10 lg:flex lg:items-center lg:justify-between lg:gap-12"><div><p className="font-mono text-[10px] uppercase tracking-[0.28em] text-[#A8792F]">Commencer simplement</p><h2 className="mt-4 max-w-2xl font-serif text-4xl leading-tight text-[#17221D]">Apportez votre projet. Nous structurons la première base.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-[#5D6A62]">Décrivez le chantier, ajoutez les dimensions connues et joignez votre plan si nécessaire.</p></div><Link href="/etude" className="mt-7 inline-flex h-12 shrink-0 items-center justify-center gap-3 bg-[#17221D] px-6 font-mono text-[10px] uppercase tracking-[0.16em] text-[#F4F0E8] lg:mt-0">Accéder à l’étude <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></div></section>

      <footer className="border-t border-[#CBD0C8] bg-[#E8E4DA]"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-6 font-mono text-[10px] uppercase tracking-[0.14em] text-[#718078] sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-12"><span>MÉTREXPERT IA PRO · Abidjan, Côte d’Ivoire</span><a href={whatsappUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-[#8A6B36] hover:text-[#17221D]"><MessageCircle className="h-3.5 w-3.5" aria-hidden="true" />WhatsApp Business</a></div></footer>
    </main>
  );
}
